# @package _global_

# Override Experiment settings
experiment:
  name: llama_logiqa_debate
  description: "Configuration for the initial debate phase using llama on logiqa"
  debug: false

# Override Debate configuration
debate:
  agents: 3
  rounds: 2
  summarize: true

# Override Model configuration
model:
  name: "llama"
  path: /ds/models/llms/Meta-Llama-3-8B-Instruct
  temperature: 1.0
  top_p: 0.9
  device: 0
  vllm: true
  vllm_mem: 0.3

# Override Dataset configuration
dataset:
  name: logiqa
  path: /ds/text/faithfulness/
  format: "multiple_choice"
  split: train
  max_rows: 1000

# Extra parameters
training:
  max_seq_length: 2048

# User's username directory
user:
  name: aagbaria
  
# Hydra configuration
hydra:
  run:
    dir: /netscratch/${user.name}/multiagent-alignment/outputs/${model.name}/debate/${dataset.name}/
